class MBHProjectile_PharaoSmall extends UTProj_LinkPlasma;

DefaultProperties
{
	ProjFlightTemplate=ParticleSystem'Pharaoh_Projectile.particle_system.Fireball'
	ProjExplosionTemplate=ParticleSystem'Pharaoh_Projectile.particle_system.Fireball_Hit'
}
